### ISSUE TITLE
No such file or directory: 'ROAR_Sim/configurations/occu_map_config.json'

### ISSUE THREAD

**Issue by NickL77** [augcog/ROAR#50]
**To Reproduce**
1. Follow QuickStart guide
2. Running `python runner_sim.py` gives the error `No such file or directory: 'ROAR_Sim/configurations/occu_map_config.json'`
3. JSON file is missing from local filesystem and the repo

**Comment by wuxiaohua1011** [comment]
Good catch, I think we pushed to ROAR_Sim master but forgot to update ROAR master. 

https://github.com/augcog/ROAR_Sim/blob/master/configurations/occu_map_config.json

For now, could you kindly download the file in the above link and copy and paste it to the location it is expecting?

**Comment by wuxiaohua1011** [comment]
Should be resolved in commit https://github.com/augcog/ROAR/commit/965655b3aabff07e60c58f3a9cd66318c9713998
