### ISSUE TITLE
find_k_values function PID Controller clips pid values

### ISSUE THREAD

**Issue by moonwonlee** [augcog/ROAR#52]
np.clip() got applied to Kp, Ki, Kd raw coefficients in find_k_values function in PIDController class.

PID values got clipped where the minimum is 0 and the maximum is 1.

1. Go to def find_k_values in  class PIDController in 'pid_controller.py'.
2. return np.clip([k_p, k_d, k_i], a_min=0, a_max=1) # this is problematic

**Expected behavior**
PID values can go over 1, for example k_p = 10000 is valid

**Additional context**
np.clip is used in 33 places across 11 files. Need to be checked.

**Comment by wuxiaohua1011** [comment]
Thanks for filing the bug. It is fixed in the newest push
